// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArYe3-pXL9Q3NCO4enn4KpWWNEP21mt4g',
    appId: '1:169688902185:web:d54ea4b801f48a76898a38',
    messagingSenderId: '169688902185',
    projectId: 'notif-75c8e',
    authDomain: 'notif-75c8e.firebaseapp.com',
    storageBucket: 'notif-75c8e.appspot.com',
    measurementId: 'G-GPPK75JS3F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5AyIIkBrJXRdKliyUoTIfUwdErut-22M',
    appId: '1:169688902185:android:00d017af146ea47b898a38',
    messagingSenderId: '169688902185',
    projectId: 'notif-75c8e',
    storageBucket: 'notif-75c8e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoQtBjZq_e1OCuMX0A5cofFSrzR86-BdE',
    appId: '1:169688902185:ios:36aba06221b9c741898a38',
    messagingSenderId: '169688902185',
    projectId: 'notif-75c8e',
    storageBucket: 'notif-75c8e.appspot.com',
    iosClientId: '169688902185-8f6j0348nvhq4tj0acc60mkb4qsomnln.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoQtBjZq_e1OCuMX0A5cofFSrzR86-BdE',
    appId: '1:169688902185:ios:36aba06221b9c741898a38',
    messagingSenderId: '169688902185',
    projectId: 'notif-75c8e',
    storageBucket: 'notif-75c8e.appspot.com',
    iosClientId: '169688902185-8f6j0348nvhq4tj0acc60mkb4qsomnln.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireFlutter',
  );
}
